openapi: 3.0.0
info:
  title: "API Tools"
  version: "1.0.0"
  description: "Описание вашего API инструмента"
paths:
  /api/tools:
    get:
      tags:
        - Tools
      summary: "Получить список инструментов"
      parameters:
        - in: query
          name: search
          schema:
            type: string
          description: "Поиск по имени инструмента"
        - in: query
          name: parent_id
          schema:
            type: integer
          description: "Фильтр по ID родительской категории"
        - in: query
          name: onlyInStock
          schema:
            type: string
            enum:
              - true
              - false
          description: "Фильтр по наличию на складе"
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: "Номер страницы для пагинации"
        - in: query
          name: limit
          schema:
            type: integer
            default: 50
          description: "Количество элементов на странице"
        - in: query
          name: param_{paramId}
          schema:
            type: string
          description: "Динамические параметры для фильтрации"
      responses:
        '200':
          description: "Список инструментов"
          content:
            application/json:
              schema:
                type: object
                properties:
                  currentPage:
                    type: integer
                  itemsPerPage:
                    type: integer
                  totalCount:
                    type: integer
                  tools:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        property:
                          type: object
                          additionalProperties:
                            type: object
                            properties:
                              label:
                                type: string
                              value:
                                type: string
                        sklad:
                          type: integer
                        norma:
                          type: string
                        group_id:
                          type: integer
                        group_standard:
                          type: string
        '500':
          description: "Внутренняя ошибка сервера"
    post:
      tags:
        - Tools
      summary: "Добавить новый инструмент"
      requestBody:
        content:
          application/json:
            schema:
              # Define the schema for the request body here
              type: object
      responses:
        '201':
          description: "Инструмент успешно добавлен"
        '400':
          description: "Некорректные данные запроса"
        '500':
          description: "Внутренняя ошибка сервера"
    put:
      tags:
        - Tools
      summary: "Обновить инструмент"
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: "ID инструмента для обновления"
      requestBody:
        content:
          application/json:
            schema:
              # Define the schema for the request body here
              type: object
      responses:
        '200':
          description: "Инструмент успешно обновлен"
        '400':
          description: "Некорректные данные запроса"
        '404':
          description: "Инструмент не найден"
        '500':
          description: "Внутренняя ошибка сервера"
    delete:
      tags:
        - Tools
      summary: "Удалить инструмент"
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: "ID инструмента для удаления"
      responses:
        '204':
          description: "Инструмент успешно удален"
        '404':
          description: "Инструмент не найден"
        '500':
          description: "Внутренняя ошибка сервера"